snowflake:
  #数据中心Id,不同模块请不要重复
  data-center-id: 1
security:
  signTImeout: 300
  ignoreSingUri: "/swagger-ui.html,/swagger-resources,/v2/api-docs,/webjars/springfox-swagger-ui,/csrf"
spring:
  profiles:
    active: #spring.profiles.active#


################### 数据库配置 start ##########################
  datasource:
    druid:
      #配置获取连接等待超时的时间
      max-wait: 60000
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j2
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      #是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions:  "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count:  1000
        profile-enable: true
      #StatViewServlet配置
      #展示Druid的统计信息,StatViewServlet的用途包括：1.提供监控信息展示的html页面2.提供监控信息的JSON API
      #是否启用StatViewServlet默认值true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      #deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝。如果allow没有配置或者为空，则允许所有访问
      #stat-view-servlet.allow=
      #stat-view-servlet.deny=128.242.127.1/24,128.242.128.1
      #Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      #aop-patterns=
################### 数据库配置 end ##########################

################### redis配置 start ##########################
  redis:
    #    host: 127.0.0.1
    #    port: 6379
    #    password:
    cluster:
      nodes: 127.0.0.1:6379
      max-redirects: 3
    database: 0
    timeout: 20000
    lettuce:
      pool:
        max-active: 10
        min-idle: 2
        max-idle: 8
        max-wait: 1000ms
      shutdown-timeout: 1000ms
################### redis配置 end ##########################

################### 缓存配置 start ##########################
  cache:
    type: redis
################### 缓存配置 end ##########################

################### json配置 start ##########################
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
################### json配置 end ##########################


################### mybatis插件 start ##########################
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  typeAliasesPackage: com.elison.platform.*.model.dao.*
  type-enums-package: com.elison.platform.*.enums.*
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", NONE:"跟随全局设置,全局设置中=INPUT",INPUT:"自定义输入", ASSIGN_ID:"全局唯一ID 雪花算法", ASSIGN_UUID:"全局唯一ID UUID";
      id-type: input
      #逻辑删除配置
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
################### mybatis插件 end ##########################